### ISSUE TITLE
time.IsZero() is not suitable for use

### ISSUE THREAD

**Issue by shunki-fujita** [cybozu-go/moco-agent#81]
**Describe the bug**

The time.IsZero() function checks to see if it matches `January 1, 1, 00:00:00 UTC`.
https://pkg.go.dev/time#Time.IsZero

The zero value in the `queued` is `0000-00-00 00:00:00.000000`, so it is not judged correctly.
https://github.com/cybozu-go/moco-agent/blob/f414f81b0e024b8bb37c384d8e4e3476992d156d/server/mysqld_health.go#L94-L96

```
mysql> SELECT MAX(LAST_QUEUED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP) FROM performance_schema.replication_connection_status;
+--------------------------------------------------------+
| MAX(LAST_QUEUED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP) |
+--------------------------------------------------------+
| 0000-00-00 00:00:00.000000                             |
+--------------------------------------------------------+
1 row in set (0.00 sec)

mysql> 
```

**Expected behavior**
Can correctly determine that `0000-00-00 00:00:00.000000` is a zero value.

**Comment by umezawatakeshi** [comment]
As far as I tested, `TIMESTAMP(6)` value `0000-00-00 00:00:00.000000` is converted to `time.Time` value `0001-01-01 00:00:00 +0000 UTC`. So the code you mentioned works as expected.

However, this behavior is not intuitive, though.
